//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by timidplayer.rc
//
#define IDI_ICON                        101
#define IDR_MAINMENU                    201
#define IDR_ACCEL                       202
#define IDD_BATCH                       301
#define IDD_JUMPTIME                    302
#define IDD_SLEEPTIMER                  303
#define IDD_PLAYLISTMGR                 304
#define IDD_STATS                       305
#define IDD_CONFIG                      306
#define IDD_DRUMDLG                     307
#define IDD_QUIETDLG                    308
#define IDD_AUDIOOUTPUT                 309
#define IDD_PLAYEROPTIONS               310
#define IDD_MIDIINPUT                   311
#define IDD_CHANMIX                     312
#define IDD_VKBD                        313
#define IDD_INJECTMIDI                  314
#define IDD_ALREADYRUNNING              315
#define IDS_APPTITLE                    401
#define IDS_WINDOWTITLEFMT              402
#define IDS_MUTEXFAILED                 403
#define IDS_COMFAILED                   404
#define IDS_MEMFAILED                   405
#define IDS_REGCLASSFAILED              406
#define IDS_CREATEWNDFAILED             407
#define IDS_ACCELFAILED                 408
#define IDS_CTRLFAILED                  409
#define IDS_SYNTHINITFAILED             410
#define IDS_ABOUTCAP                    411
#define IDS_ABOUTTXT                    412
#define IDS_ALREADYRUNNING              413
#define IDS_ALREADYRUNNINGQ             414
#define IDS_MIDFLT                      415
#define IDS_MIDCAP                      416
#define IDS_OUTCAP                      417
#define IDS_CFGFLT                      418
#define IDS_CFGCAP                      419
#define IDS_INSTFLT                     420
#define IDS_INSTCAP                     421
#define IDS_WAVFLT                      422
#define IDS_WAVCAP                      423
#define IDS_M3UFLT                      424
#define IDS_M3UOPENCAP                  425
#define IDS_M3USAVECAP                  426
#define IDS_CSVFLT                      427
#define IDS_CSVCAP                      428
#define IDS_SETTINGSFLT                 429
#define IDS_SETTINGSOPENCAP             430
#define IDS_SETTINGSSAVECAP             431
#define IDS_PLAYLISTLABEL               432
#define IDS_PAUSELABEL                  433
#define IDS_PLAYLABEL                   434
#define IDS_ALWAYSONTOPMENU             435
#define IDS_STATEPLAYING                436
#define IDS_STATEPAUSED                 437
#define IDS_STATESTOPPED                438
#define IDS_STATENOFILE                 439
#define IDS_STATEMIDIIN                 440
#define IDS_STATUSTRACKFMT              441
#define IDS_STATUSFMT                   442
#define IDS_VOICESFMT                   443
#define IDS_VOLFMT                      444
#define IDS_CPUFMT                      445
#define IDS_NOFILELOADED                446
#define IDS_LOADFAILED                  447
#define IDS_WAVEOUTFAILED               448
#define IDS_MIDIINFAILED                449
#define IDS_CONFIGAPPLYFAILED           450
#define IDS_M3ULOADFAILED               451
#define IDS_M3USAVEFAILED               452
#define IDS_M3UNOPLAYLIST               453
#define IDS_ADDQUEUETOBATCH             454
#define IDS_CONFIRMDELETEPLAYLISTITEM   455
#define IDS_CMDLINE_NOFILES             456
#define IDS_STATSFILE                   457
#define IDS_STATSNONE                   458
#define IDS_STATSTITLE                  459
#define IDS_STATSCOPYRIGHT              460
#define IDS_STATSEVENTS                 461
#define IDS_STATSDURATION               462
#define IDS_STATSPOSITION               463
#define IDS_STATSBITRATE                464
#define IDS_STATSVOICES                 465
#define IDS_STATSLOST                   466
#define IDS_STATSCUT                    467
#define IDS_STATSCPU                    468
#define IDS_JUMPTIMEFORMAT              469
#define IDS_SLEEPMINUTESFORMAT          470
#define IDS_RECENTEMPTY                 471
#define IDS_WAVEMAPPER                  472
#define IDS_MIDIINMAPPER                473
#define IDS_UNKNOWNDEVICE               474
#define IDS_FMT_8BITINT                 475
#define IDS_FMT_16BITINT                476
#define IDS_FMT_24BITINT                477
#define IDS_FMT_32BITINT                478
#define IDS_FMT_32BITFLOAT              479
#define IDS_FMT_64BITFLOAT              480
#define IDS_FMT_8BITULAW                481
#define IDS_CONVERTINGWAVFMT            482
#define IDS_QUICKCONVERTDONE            483
#define IDS_QUICKCONVERTINPROGRESS      484
#define IDS_QUICKCONVERTBUSY            485
#define IDS_CONVERTCURRENTBUSY          486
#define IDS_BATCHCONVERTERBUSY          487
#define IDS_QC_SYNTHFAILED              488
#define IDS_QC_LOADFAILED               489
#define IDS_QC_CREATEFAILED             490
#define IDS_QC_OUTOFMEMORY              491
#define IDS_QC_WRITEFAILED              492
#define IDS_NOFILES                     493
#define IDS_CREATEDIR                   494
#define IDS_CREATEDIRFAIL               495
#define IDS_SUMMARY                     496
#define IDS_BATCHINITFAILED             497
#define IDS_BATCHCONVERTINPROGRESS      498
#define IDS_CANCELBTN                   499
#define IDS_CONVERTBTN                  500
#define IDS_CONVERTINGSTATUSFMT         501
#define IDS_OUTDIRSAVED                 502
#define IDS_RESULT_LOADFAILED           503
#define IDS_RESULT_WRITEFAILED          504
#define IDS_RESULT_SKIPPED              505
#define IDS_RESULT_LOSTCUT              506
#define IDS_RESULT_SPEED                507
#define IDS_RESULT_TITLE                508
#define IDS_RESULT_COPYRIGHT            509
#define IDS_RESULT_DURATION             510
#define IDS_RESULT_EVENTS               511
#define IDS_RESULT_BITRATE              512
#define IDS_CSVHEADER                   513
#define IDS_CSVSAVEFAILED               514
#define IDS_CSVSAVED                    515
#define IDS_OUTCOME_CONVERTED           516
#define IDS_OUTCOME_LOADFAILED          517
#define IDS_OUTCOME_WRITEFAILED         518
#define IDS_OUTCOME_SKIPPED             519
#define IDS_OUTCOME_PENDING             520
#define IDS_TRAYRESTORE                 521
#define IDS_TRAYEXIT                    522
#define IDS_TRAYPANIC                   523
#define IDS_TRAYRESET                   524
#define IDS_CONTEXTPLAY                 525
#define IDS_CONTEXTREMOVE               526
#define IDS_CONTEXTSTATS                527
#define IDS_CONTEXTCONVERT              528
#define IDS_INJECT_NOTEOFF              529
#define IDS_INJECT_NOTEON               530
#define IDS_INJECT_POLYAFTERTOUCH       531
#define IDS_INJECT_CONTROLCHANGE        532
#define IDS_INJECT_PROGRAMCHANGE        533
#define IDS_INJECT_PITCHBEND            534
#define IDS_CONFIRMRESTOREDEFAULTS      535
#define IDS_SETTINGSRESTORED            536
#define IDS_CONFIRMIMPORTSETTINGS       537
#define IDS_SETTINGSIMPORTED            538
#define IDS_SETTINGSEXPORTED            539
#define IDS_DELETESETTINGSFAILED        540
#define IDS_EXPORTSETTINGSFAILED        541
#define IDS_IMPORTSETTINGSFAILED        542
#define IDS_ADDFOLDERCAP                543
#define IDS_CONFIRMSAVEPLAYLISTONEXIT   544
#ifndef IDC_STATIC
#define IDC_STATIC                      -1
#endif
#define IDC_STATUSBAR                   1001
#define IDC_SEEKBAR                     1002
#define IDC_PLAYLISTVIEW                1003
#define IDC_FILELIST                    1004
#define IDC_ADDFILES                    1005
#define IDC_ADDFOLDER                   1006
#define IDC_REMOVE                      1007
#define IDC_CLEARALL                    1008
#define IDC_MOVEUP                      1009
#define IDC_MOVEDOWN                    1010
#define IDC_OUTDIR                      1011
#define IDC_OUTDIRB                     1012
#define IDC_OUTDIRDEFAULT               1013
#define IDC_OVERWRITE                   1014
#define IDC_PRESERVEDIRS                1015
#define IDC_OUTFORMAT                   1016
#define IDC_PROGRESS                    1017
#define IDC_STATUS                      1018
#define IDC_CONVERT                     1019
#define IDC_SAVECSV                     1020
#define IDC_JUMPTIME                    1021
#define IDC_SLEEPMINUTES                1022
#define IDC_PLMGRSEARCH                 1023
#define IDC_PLMGRLIST                   1024
#define IDC_PLMGRPLAY                   1025
#define IDC_PLMGRUP                     1026
#define IDC_PLMGRDOWN                   1027
#define IDC_PLMGRDELETE                 1028
#define IDC_STATSLIST                   1029
#define IDC_STATSREFRESH                1030
#define IDC_CFG                         1031
#define IDC_CFGB                        1032
#define IDC_SAMPRATE                    1033
#define IDC_CTRATE                      1034
#define IDC_CTRATES                     1035
#define IDC_VOICES                      1036
#define IDC_VOICESS                     1037
#define IDC_AMP                         1038
#define IDC_AMPS                        1039
#define IDC_PAN                         1040
#define IDC_MONO                        1041
#define IDC_8BIT                        1042
#define IDC_ANTI                        1043
#define IDC_PRERES                      1044
#define IDC_FASTDEC                     1045
#define IDC_DYNALOAD                    1046
#define IDC_DEFINST                     1047
#define IDC_DEFINSTB                    1048
#define IDC_DEFPROG                     1049
#define IDC_DEFPROGS                    1050
#define IDC_DRUMCHANNELS                1051
#define IDC_QUIETCHANNELS               1052
#define IDC_REVERBENABLED               1053
#define IDC_REVERBONLY                  1054
#define IDC_REVERBLEVEL                 1055
#define IDC_REVERBPRESET                1056
#define IDC_CHORUSENABLED               1057
#define IDC_CHORUSDEPTH                 1058
#define IDC_DITHERENABLED               1059
#define IDC_APPLY                       1060
#define IDC_DCHAN01                     1061
#define IDC_DCHAN02                     1062
#define IDC_DCHAN03                     1063
#define IDC_DCHAN04                     1064
#define IDC_DCHAN05                     1065
#define IDC_DCHAN06                     1066
#define IDC_DCHAN07                     1067
#define IDC_DCHAN08                     1068
#define IDC_DCHAN09                     1069
#define IDC_DCHAN10                     1070
#define IDC_DCHAN11                     1071
#define IDC_DCHAN12                     1072
#define IDC_DCHAN13                     1073
#define IDC_DCHAN14                     1074
#define IDC_DCHAN15                     1075
#define IDC_DCHAN16                     1076
#define IDC_QCHAN01                     1077
#define IDC_QCHAN02                     1078
#define IDC_QCHAN03                     1079
#define IDC_QCHAN04                     1080
#define IDC_QCHAN05                     1081
#define IDC_QCHAN06                     1082
#define IDC_QCHAN07                     1083
#define IDC_QCHAN08                     1084
#define IDC_QCHAN09                     1085
#define IDC_QCHAN10                     1086
#define IDC_QCHAN11                     1087
#define IDC_QCHAN12                     1088
#define IDC_QCHAN13                     1089
#define IDC_QCHAN14                     1090
#define IDC_QCHAN15                     1091
#define IDC_QCHAN16                     1092
#define IDC_AUDIODEVICE                 1093
#define IDC_BUFFERMS                    1094
#define IDC_BUFFERMSS                   1095
#define IDC_CHUNKMS                     1096
#define IDC_CHUNKMSS                    1097
#define IDC_INTERCEPTVOLUMEKEYS         1098
#define IDC_OPT_LOADPLAYLIST            1099
#define IDC_OPT_LOADINTORUNNING         1100
#define IDC_OPT_SHOWFILENAMEINTITLE     1101
#define IDC_OPT_PREVENTDUPLICATES       1102
#define IDC_OPT_SAVETRACK               1103
#define IDC_OPT_SAVEPOSITION            1104
#define IDC_OPT_AUTOSTART               1105
#define IDC_OPT_REMOVEONUNLOAD          1106
#define IDC_OPT_CONFIRMDELETE           1107
#define IDC_OPT_PREVENTSEEKCHANGE       1108
#define IDC_OPT_AUTOSCROLLPLAYLIST      1109
#define IDC_OPT_RUNFROMTRAY             1110
#define IDC_MIDIIN_ENABLE               1111
#define IDC_MIDIIN_DEVICE               1112
#define IDC_MIDIIN_CHANMAP0             1113
#define IDC_MIDIIN_CHANMAP1             1114
#define IDC_MIDIIN_CHANMAP2             1115
#define IDC_MIDIIN_CHANMAP3             1116
#define IDC_MIDIIN_CHANMAP4             1117
#define IDC_MIDIIN_CHANMAP5             1118
#define IDC_MIDIIN_CHANMAP6             1119
#define IDC_MIDIIN_CHANMAP7             1120
#define IDC_MIDIIN_CHANMAP8             1121
#define IDC_MIDIIN_CHANMAP9             1122
#define IDC_MIDIIN_CHANMAP10            1123
#define IDC_MIDIIN_CHANMAP11            1124
#define IDC_MIDIIN_CHANMAP12            1125
#define IDC_MIDIIN_CHANMAP13            1126
#define IDC_MIDIIN_CHANMAP14            1127
#define IDC_MIDIIN_CHANMAP15            1128
#define IDC_CHANMIX_CHANNEL             1129
#define IDC_CHANMIX_INSTR               1130
#define IDC_CHANMIX_BANK                1131
#define IDC_CHANMIX_MUTE                1132
#define IDC_CHANMIX_DRUM                1133
#define IDC_CHANMIX_VOLUME              1134
#define IDC_CHANMIX_VOLUMETXT           1135
#define IDC_CHANMIX_EXPRESSION          1136
#define IDC_CHANMIX_EXPRESSIONTXT       1137
#define IDC_CHANMIX_PAN                 1138
#define IDC_CHANMIX_PANTXT              1139
#define IDC_CHANMIX_PITCHBEND           1140
#define IDC_CHANMIX_PITCHBENDTXT        1141
#define IDC_CHANMIX_PITCHRANGE          1142
#define IDC_CHANMIX_PITCHRANGETXT       1143
#define IDC_CHANMIX_MODULATION          1144
#define IDC_CHANMIX_MODULATIONTXT       1145
#define IDC_CHANMIX_REVERB              1146
#define IDC_CHANMIX_REVERBTXT           1147
#define IDC_CHANMIX_CHORUS              1148
#define IDC_CHANMIX_CHORUSTXT           1149
#define IDC_CHANMIX_SUSTAIN             1150
#define IDC_CHANMIX_MONO                1151
#define IDC_CHANMIX_NOTESOFF            1152
#define IDC_CHANMIX_SOUNDSOFF           1153
#define IDC_CHANMIX_RESETCTRL           1154
#define IDC_VKBD_CHANNEL                1155
#define IDC_VKBD_VELOCITY               1156
#define IDC_VKBD_VELOCITYTXT            1157
#define IDC_VKBD_OCTDOWN                1158
#define IDC_VKBD_RANGE                  1159
#define IDC_VKBD_OCTUP                  1160
#define IDC_VKBD_SUSTAIN                1161
#define IDC_VKBD_PRESSURE               1162
#define IDC_VKBD_PRESSURETXT            1163
#define IDC_VKBD_KEYBASE                1164
#define IDC_INJECT_CHANNEL              1188
#define IDC_INJECT_EVENTTYPE            1189
#define IDC_INJECT_DATA1                1190
#define IDC_INJECT_DATA1S               1191
#define IDC_INJECT_DATA2                1192
#define IDC_INJECT_DATA2S               1193
#define IDC_INJECT_SEND                 1194
#define IDC_ALREADYRUNNINGTEXT          1195
#define IDC_DONTASKAGAIN                1196
#define ID_FILE_OPEN                    2001
#define ID_FILE_ADDFILES                2002
#define ID_FILE_ADDFOLDER               2003
#define ID_FILE_PASTE                   2004
#define ID_FILE_RECENT_EMPTY            2005
#define ID_FILE_RECENT1                 2006
#define ID_FILE_RECENT2                 2007
#define ID_FILE_RECENT3                 2008
#define ID_FILE_RECENT4                 2009
#define ID_FILE_RECENT5                 2010
#define ID_FILE_RECENT6                 2011
#define ID_FILE_RECENT7                 2012
#define ID_FILE_RECENT8                 2013
#define ID_FILE_CLEARRECENTFILES        2014
#define ID_FILE_OPENPLAYLIST            2015
#define ID_FILE_SAVEPLAYLIST            2016
#define ID_FILE_UNLOAD                  2017
#define ID_FILE_CLEARPLAYLIST           2018
#define ID_FILE_CONVERTCURRENT          2019
#define ID_FILE_BATCHCONVERT            2020
#define ID_FILE_EXIT                    2021
#define ID_PLAYBACK_PLAYPAUSE           2022
#define ID_PLAYBACK_STOP                2023
#define ID_PLAYBACK_NEXTTRACK           2024
#define ID_PLAYBACK_PREVTRACK           2025
#define ID_PLAYBACK_FIRSTTRACK          2026
#define ID_PLAYBACK_LASTTRACK           2027
#define ID_SEEK_FORWARD                 2028
#define ID_SEEK_BACK                    2029
#define ID_PLAYBACK_RESTART             2030
#define ID_PLAYBACK_JUMPTOEND           2031
#define ID_PLAYBACK_JUMPTOTIME          2032
#define ID_PLAYBACK_SLEEPTIMER          2033
#define ID_PLAYBACK_SHUFFLE             2034
#define ID_PLAYBACK_MANAGEPLAYLIST      2035
#define ID_PLAYBACK_REPEATOFF           2036
#define ID_PLAYBACK_REPEATONE           2037
#define ID_PLAYBACK_REPEATALL           2038
#define ID_PLAYBACK_STATS               2039
#define ID_VOLUME_UP                    2040
#define ID_VOLUME_DOWN                  2041
#define ID_CONFIGURE_TIMIDITY           2042
#define ID_CONFIGURE_AUDIOOUTPUT        2043
#define ID_CONFIGURE_PLAYEROPTIONS      2044
#define ID_CONFIGURE_MIDIINPUT          2045
#define ID_CONFIGURE_EXPORTSETTINGS     2046
#define ID_CONFIGURE_IMPORTSETTINGS     2047
#define ID_CONFIGURE_RESTOREDEFAULTS    2048
#define ID_TOOLS_CHANNELMIXER           2049
#define ID_TOOLS_VKBD                   2050
#define ID_TOOLS_INJECTMIDI             2051
#define ID_RESET_ALLNOTESOFF            2052
#define ID_RESET_ALLSOUNDSOFF           2053
#define ID_RESET_RESETCONTROLLERS       2054
#define ID_RESET_PANIC                  2055
#define ID_RESET_RESET                  2056
#define ID_ENGINE_RELOADCONFIG          2057
#define ID_ENGINE_RELOADSMF             2058
#define ID_ENGINE_FORCEINSTRUMENTLOAD   2059
#define ID_ENGINE_FREEDEFAULTINSTRUMENT 2060
#define ID_ENGINE_UNLOADCONFIG          2061
#define ID_ENGINE_RESTOREDEFAULTS       2062
#define ID_VIEW_STATUSBAR               2063
#define ID_VIEW_SEEKBAR                 2064
#define ID_VIEW_PLAYLISTVIEW            2065
#define ID_HELP_ABOUT                   2066
#define ID_TRAY_RESTORE                 2067
#define ID_CONTEXT_PLAY                 2068
#define ID_CONTEXT_REMOVE               2069

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        316
#define _APS_NEXT_COMMAND_VALUE         2070
#define _APS_NEXT_CONTROL_VALUE         1197
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
